baseURL = 'https://nareshvnit.github.io/'
languageCode = 'en-us'
title = 'Naresh Kumar - Personal Website'
theme = 'personal'

[params]
  description = 'Personal website and technical blog'
  author = 'Naresh Kumar'
  email = 'naresh.nitngp@gmail.com'
  github = 'nareshvnit'
  linkedin = 'yourprofile'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'About'
    url = '/about/'
    weight = 1
  [[menu.main]]
    name = 'Experience'
    url = '/experience/'
    weight = 2
  [[menu.main]]
    name = 'Blog'
    url = '/posts/'
    weight = 3
